import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

let prod = (process.argv[2] === 'production');

const esbuildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins],
  format: 'cjs',
  target: 'ES6',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outdir: 'build',
  outbase: '.',
};

// Copy manifest.json and styles.css to build folder after build
const copyFilesPlugin = {
  name: 'copy-files',
  setup(build) {
    build.onEnd(() => {
      // Ensure build directory exists
      if (!fs.existsSync('build')) {
        fs.mkdirSync('build');
      }
      // Copy manifest.json
      fs.copyFileSync('manifest.json', 'build/manifest.json');
      // Copy styles.css
      fs.copyFileSync('styles.css', 'build/styles.css');
      console.log('Copied manifest.json and styles.css to build folder');
    });
  },
};

esbuildOptions.plugins = [copyFilesPlugin];

if (prod) {
  esbuild.build(esbuildOptions).catch(() => process.exit(1));
} else {
  esbuild.context(esbuildOptions).then(ctx => ctx.watch()).catch(() => process.exit(1));
}
